author: RK
title: RK's Notes
description: >
  Notes about things I'm interested in.
encoding: UTF-8
permalink: pretty
exclude: ["google49412ec2098884ad.html"]
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
gfm_quirks: paragraph_end
minima:
  date_format: "%Y-%m-%d %H:%M %Z"
theme: minima
github_username: z49x2vmq
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
disqus:
  shortname: z49x2vmq
timezone: Asia/Seoul
logo: /assests/wire.jpg
google_analytics: UA-109701028-1
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
     author: "RK"
     layout: "post"
     image: "NA"
