author: Rae Kim
title: RK's Notes
description: >
  이것저것 여러분야 관심사를 메모하기 위한 블로그. Powered by Jekyll
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
gfm_quirks: paragraph_end
minima:
  date_format: "%Y-%m-%d %H:%M %Z"
theme: minima
github_username: z49x2vmq
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
disqus:
  shortname: z49x2vmq
timezone: Asia/Seoul
