title: RK's Notes
description: >
  이것 저것 메모하는 곳
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
gfm_quirks: paragraph_end
minima:
  date_format: "%Y-%m-%d %H:%M %Z"
theme: minima
github_username: z49x2vmq
minima:
  date_format: "%Y-%m-%d %H:%M %Z"
plugins:
  - jekyll-sitemap
